### ISSUE TITLE
MBDefines

### ISSUE THREAD

**Issue by Aaronov** [demosdemon/libmusicbrainz-objc#1]
There seems to be a missing python script for generating the MBGeneratedDefines.h

**Comment by demosdemon** [comment]
Hmm, I'm not quite sure what issue you're having. The script (though it does need to be moved) is located at `./libmusicbrainz-objc.xcodeproj/MBGeneratedDefines.py`. I did a fresh clone and am having no problems with it. Do you have an error message or anything that can help me figure this out?

**Comment by Aaronov** [comment]
Sorry disregard what I said. I was trying to include the lib in my project without including your project file which is why the file wasn't being found and I was looking on the file system for it instead of in the project. Cheers.
